package note;

public class WinKeyCode {
  public static final int VK_LBUTTON = 1; //鼠标左键
  public static final int VK_RBUTTON = 2; //鼠标右键
  public static final int VK_CANCEL = 3; //Cancel
  public static final int VK_MBUTTON = 4; //鼠标中键
  public static final int VK_XBUTTON1 = 5; //
  public static final int VK_XBUTTON2 = 6; //
  public static final int VK_BACK = 8; //Backspace
  public static final int VK_TAB = 9; //Tab
  public static final int VK_CLEAR = 12; //Clear
  public static final int VK_RETURN = 13; //Enter
  public static final int VK_SHIFT = 16; //Shift
  public static final int VK_CONTROL = 17; //Ctrl
  public static final int VK_MENU = 18; //Alt
  public static final int VK_PAUSE = 19; //Pause
  public static final int VK_CAPITAL = 20; //Caps Lock
  public static final int VK_KANA = 21;
  public static final int VK_HANGUL = 21; //
  public static final int VK_JUNJA = 23; //
  public static final int VK_FINAL = 24; //
  public static final int VK_HANJA = 25; //
  public static final int VK_KANJI = 25; //
  public static final int VK_ESCAPE = 27; // Esc
  public static final int VK_CONVERT = 28; //
  public static final int VK_NONCONVERT = 29; //
  public static final int VK_ACCEPT = 30; //
  public static final int VK_MODECHANGE = 31; //
  public static final int VK_SPACE = 32; //Space
  public static final int VK_PRIOR = 33; //Page Up
  public static final int VK_NEXT = 34; //Page Down
  public static final int VK_END = 35; //End
  public static final int VK_HOME = 36; //Home
  public static final int VK_LEFT = 37; //Left Arrow
  public static final int VK_UP = 38; //Up Arrow
  public static final int VK_RIGHT = 39; //Right Arrow
  public static final int VK_DOWN = 40; //Down Arrow
  public static final int VK_SELECT = 41; // Select
  public static final int VK_PRINT = 42; //Print
  public static final int VK_EXECUTE = 43; //Execute
  public static final int VK_SNAPSHOT = 44; //Snapshot
  public static final int VK_INSERT = 45; //Insert
  public static final int VK_DELETE = 46; //Delete
  public static final int VK_HELP = 47; //Help
  public static final int VK_LWIN = 91; //
  public static final int VK_RWIN = 92; //
  public static final int VK_APPS = 93; //
  public static final int VK_SLEEP = 95; //
  public static final int VK_NUMPAD0 = 96; //小键盘 0
  public static final int VK_NUMPAD1 = 97; //小键盘 1
  public static final int VK_NUMPAD2 = 98; //小键盘 2
  public static final int VK_NUMPAD3 = 99; //小键盘 3
  public static final int VK_NUMPAD4 = 100; //小键盘 4
  public static final int VK_NUMPAD5 = 101; //小键盘 5
  public static final int VK_NUMPAD6 = 102; //小键盘 6
  public static final int VK_NUMPAD7 = 103; //小键盘 7
  public static final int VK_NUMPAD8 = 104; //小键盘 8
  public static final int VK_NUMPAD9 = 105; //小键盘 9
  public static final int VK_MULTIPLY = 106; //小键盘 *
  public static final int VK_ADD = 107; //小键盘 +
  public static final int VK_SEPARATOR = 108; //小键盘 Enter
  public static final int VK_SUBTRACT = 109; //小键盘 -
  public static final int VK_DECIMAL = 110; //小键盘 .
  public static final int VK_DIVIDE = 111; //小键盘 /
  public static final int VK_F1 = 112; //F1</td>
  public static final int VK_F2 = 113; //F2</td>
  public static final int VK_F3 = 114; //F3</td>
  public static final int VK_F4 = 115; //F4</td>
  public static final int VK_F5 = 116; //F5</td>
  public static final int VK_F6 = 117; //F6</td>
  public static final int VK_F7 = 118; //F7</td>
  public static final int VK_F8 = 119; //F8</td>
  public static final int VK_F9 = 120; //F9</td>
  public static final int VK_F10 = 121; //F10</td>
  public static final int VK_F11 = 122; //F11</td>
  public static final int VK_F12 = 123; //F12</td>
  public static final int VK_F13 = 124; //
  public static final int VK_F14 = 125; //
  public static final int VK_F15 = 126; //
  public static final int VK_F16 = 127; //
  public static final int VK_F17 = 128; //
  public static final int VK_F18 = 129; //
  public static final int VK_F19 = 130; //
  public static final int VK_F20 = 131; //
  public static final int VK_F21 = 132; //
  public static final int VK_F22 = 133; //
  public static final int VK_F23 = 134; //
  public static final int VK_F24 = 135; //
  public static final int VK_NUMLOCK = 144; //Num Lock
  public static final int VK_SCROLL = 145; //Scroll
  public static final int VK_LSHIFT = 160; //
  public static final int VK_RSHIFT = 161; //
  public static final int VK_LCONTROL = 162; //
  public static final int VK_RCONTROL = 163; //
  public static final int VK_LMENU = 164; //
  public static final int VK_RMENU = 165; //
  public static final int VK_BROWSER_BACK = 166; //
  public static final int VK_BROWSER_FORWARD = 167; //
  public static final int VK_BROWSER_REFRESH = 168; //
  public static final int VK_BROWSER_STOP = 169; //
  public static final int VK_BROWSER_SEARCH = 170; //
  public static final int VK_BROWSER_FAVORITES = 171; //
  public static final int VK_BROWSER_HOME = 172; //
  public static final int VK_VOLUME_MUTE = 173; //VolumeMute
  public static final int VK_VOLUME_DOWN = 174; // VolumeDown
  public static final int VK_VOLUME_UP = 175; //VolumeUp
  public static final int VK_MEDIA_NEXT_TRACK = 176; //
  public static final int VK_MEDIA_PREV_TRACK = 177; //
  public static final int VK_MEDIA_STOP = 178; //
  public static final int VK_MEDIA_PLAY_PAUSE = 179; //
  public static final int VK_LAUNCH_MAIL = 180; //
  public static final int VK_LAUNCH_MEDIA_SELECT = 181; //
  public static final int VK_LAUNCH_APP1 = 182; //
  public static final int VK_LAUNCH_APP2 = 183; //
  public static final int VK_OEM_1 = 186; //;
  public static final int VK_OEM_PLUS = 187; // +
  public static final int VK_OEM_COMMA = 188; //=
  public static final int VK_OEM_MINUS = 189; //- _
  public static final int VK_OEM_PERIOD = 190; //
  public static final int VK_OEM_2 = 191; /// ?
  public static final int VK_OEM_3 = 192; //` ~
  public static final int VK_OEM_4 = 219; //[ {
  public static final int VK_OEM_5 = 220; // \ |
  public static final int VK_OEM_6 = 221; //] }
  public static final int VK_OEM_7 = 222 ; //' &quot;
  public static final int VK_OEM_8 = 223; //
  public static final int VK_OEM_102 = 226; //
  public static final int VK_PACKET = 231; //
  public static final int VK_PROCESSKEY = 229; //
  public static final int VK_ATTN = 246; //
  public static final int VK_CRSEL = 247; //
  public static final int VK_EXSEL = 248; //
  public static final int VK_EREOF = 249; //
  public static final int VK_PLAY = 250; //
  public static final int VK_ZOOM = 251; //
  public static final int VK_NONAME = 252; //
  public static final int VK_PA1 = 253; //
  public static final int VK_OEM_CLEAR = 254; //
}
